### PR TITLE
refactor: update old metabolites IDs in svg maps

### PR DESCRIPTION
**Pull request by inghylt**

### CODE REVIEW

**Comment by e0** [comment]
I notice that some of the metabolite ids do not have the same format in the `metabolites.tsv` file compared with the SVG files. For example in `cytosol_1.svg`, the metabolite ids containing the characters `mpdol` do not have any exact matches. Some examples:

1. `m2mpdol` in `metabolites.tsv` vs `m2mpdol_U_c` and `m2mpdol_L_c` in `cytosol_1.svg`
2. `m4mpdol__L` in `metabolites.tsv` vs `m3mpdol_U_c` and `m3mpdol_L_c` in `cytosol_1.svg`

Note that in the 1st case, there are two different ids in the SVG but only one line in `metabolites.tsv`.

```tsv
"MAM01865c"	"MAM01865"	"m2mpdol"	"G00005"	""	""	""	""	""	""	"M01865"	"MNXM9296"	"m01865c"	"m01865c"
```

In the 2nd case, there are two different ids in the SVG and two lines in `metabolites.tsv`.

```tsv
"MAM01866c"	"MAM01866"	"m4mpdol__L"	"C05864"	""	"CHEBI:37633"	""	""	""	""	"m4mpdol_L"	"MNXM147337"	"m01866c"	"m01866c"
"MAM01866r"	"MAM01866"	"m4mpdol__L"	"C05864"	""	"CHEBI:37633"	""	""	""	""	"m4mpdol_L"	"MNXM147337"	"m01866r"	"m01866r"

```

**Comment by mihai-sysbio** [comment]
@e0 what you have observed is likely the update of the model, and the maps being out of sync. The IDs should be replaced wherever it is possible, but in all these cases where some ids have been renamed or removed from the model, there is not much that can be done. Once could mark regex the lines containing non-updated ids and remove them, or even better regenerate the maps from scratch, but both of these ideas are outside the scope of this issue.

**Review by mihai-sysbio — APPROVED** [review]
Looks good to me. One suggestion I can think of is to use a single script with different params and options, for example:
```
[ { path: `metabolites.tsv`, origColumn: 13, newColumn: 0, options: regexOrFunctionUsedToReplaceUpToYou }, ...]
```
For the reactions there could be different entries or alternatively the options could be an array itself.

**Comment by mihai-sysbio** [comment]
The next step here is to remove the unmappable reaction ids from the maps listed below, as described in https://github.com/MetabolicAtlas/private-issues/issues/130:

- [ ] bile_acid_biosynthesis.svg
- [ ] blood_group_biosynthesis.svg
- [ ] cholesterol_metabolism.svg
- [ ] cysteine_and_methionine_metabolism.svg
- [ ] eicosanoid_metabolism.svg
- [ ] glycerophospholipid_metabolism.svg
- [ ] glycolysis_gluconeogenesis.svg
- [ ] histidine_metabolism.svg
- [ ] lysine_metabolism.svg
- [ ] n_glycan_metabolism.svg
- [ ] omega_6_fatty_acid_metabolism.svg
- [ ] sphingolipid_metabolism.svg
- [ ] starch_and_sucrose_metabolism.svg
- [ ] steroid_metabolism.svg
- [ ] triacylglycerol_synthesis.svg
- [ ] tyrosine_metabolism.svg
- [ ] vitamin_a_metabolism.svg
- [ ] vitamin_d_metabolism.svg

**Comment by mihai-sysbio** [comment]
I've done the following steps for `glycerophospholipid_metabolism`.
- remove the rows:
```
    <path class="fe TODO
    <path class="feh TODO
    <path class="ee TODO
    <g id="TODO and 5 rows after
```

- cleanup up all metabolite nodes containing `TODO` either by removing the svg node or, when that node has multiple reaction ids, removing the node id from the list.
- removed all gene nodes containing `TODO`
- removed all occurrences of `TODO` that mistakenly modified the gene text label

⚠️ there are still un-mappable reaction ids in the svg, of the form `*MAR\d+`, as if there is a missing space between a "bad" id and a "good" id, but it could also be a replacement issue.

**Comment by inghylt** [comment]
acylglycerides_metabolism.svg
bile_acid_biosynthesis.svg
glycerophospholipid_metabolism.svg

Needs to be rerun through the entire pipeline. Use scripts in commit 1be8973

**Comment by mihai-sysbio** [comment]
In the last commit 59e1038 I have removed the background highlighting, where needed. I think this was the last step to finish the map updates. @inghylt am I missing something?

**Review by mihai-sysbio — APPROVED** [review]
🌟

**Pull request merged**
